default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: FALPBX_development
test:
  <<: *default
  database: FALPBX_test
production:
  <<: *default
  database: FALPBX_production
  username: FALPBX
  password: <%= ENV['FALPBX_DATABASE_PASSWORD'] %>
